#lang scheme
(require (planet schematics/schemeunit:3))

(define (pascals-triangle row n)
  (cond ((= 1 n) 1)
        ((= row n) 1)
        (else (+ (pascals-triangle (- row 1) (- n 1))
                 (pascals-triangle (- row 1) n)))))
        
(check-equal? (pascals-triangle 1 1) 1)
(check-equal? (pascals-triangle 2 1) 1)
(check-equal? (pascals-triangle 2 2) 1)
(check-equal? (pascals-triangle 3 1) 1)
(check-equal? (pascals-triangle 3 2) 2)
(check-equal? (pascals-triangle 3 3) 1)
(check-equal? (pascals-triangle 4 1) 1)
(check-equal? (pascals-triangle 4 2) 3)
(check-equal? (pascals-triangle 4 3) 3)
(check-equal? (pascals-triangle 4 4) 1)
(check-equal? (pascals-triangle 5 1) 1)
(check-equal? (pascals-triangle 5 2) 4)
(check-equal? (pascals-triangle 5 3) 6)
(check-equal? (pascals-triangle 5 4) 4)
(check-equal? (pascals-triangle 5 5) 1)
